### ISSUE TITLE
Feature: User can search event or artist

### ISSUE THREAD

**Issue by cathyygrcia** [cathyygrcia/ajax-project#1]
## 📐 Functionality

> ##### User should be able to search by artist name or genre. Whenever user refreshes the page, a random selection of events will be displayed.

## Wireframe

![Screen Shot 2023-08-15 at 4 23 10 PM](https://github.com/cathyygrcia/ajax-project/assets/90016242/f4c284f2-ce35-468a-a6e4-7a04c81fa341)

![Screen Shot 2023-08-15 at 4 23 29 PM](https://github.com/cathyygrcia/ajax-project/assets/90016242/342375ef-ba2f-4860-a2c9-4d48ef1872a0)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Complete HTML and CSS so that it matches the figma example
- [x] Write CSS for mobile devices
- [x] Create search bar
- [x] Create addEventListener function for when user searches artist / genre
       - [ ] Utilize the XMLHttpRequest to make a request the API
      - [ ]  When the form is submitted retrieve the users input
      - [ ]  update the DOM tree with the search responses
- [x] Create a function getEvents that makes a request to the tickmaster API 
       - [ ] Utilize the XMLHttpRequest to make a request the API
       - [ ] Loop over the response and create a DOM tree for each event
       - [ ] fix styling for the event images
